<script>
export const countryCodeDict = {
  Afghanistan: 'af',
  Albania: 'al',
  Algeria: 'dz',
  Andorra: 'ad',
  Angola: 'ao',
  'Antigua and Barbuda': 'ag',
  Argentina: 'ar',
  Armenia: 'am',
  Australia: 'au',
  Austria: 'at',
  Azerbaijan: 'az',
  Bahamas: 'bs',
  Bahrain: 'bh',
  Bangladesh: 'bd',
  Barbados: 'bb',
  Belarus: 'by',
  Belgium: 'be',
  Belize: 'bz',
  Benin: 'bj',
  Bhutan: 'bt',
  Bolivia: 'bo',
  'Bosnia and Herzegovina': 'ba',
  Botswana: 'bw',
  Brazil: 'br',
  Brunei: 'bn',
  Bulgaria: 'bg',
  'Burkina Faso': 'bf',
  Burundi: 'bi',
  'Cabo Verde': 'cv',
  Cambodia: 'kh',
  Cameroon: 'cm',
  Canada: 'ca',
  'Central African Republic': 'cf',
  Chad: 'td',
  Chile: 'cl',
  China: 'cn',
  Colombia: 'co',
  Comoros: 'km',
  'Congo (Congo-Brazzaville)': 'cg',
  'Costa Rica': 'cr',
  Croatia: 'hr',
  Cuba: 'cu',
  Cyprus: 'cy',
  'Czechia (Czech Republic)': 'cz',
  'Democratic Republic of the Congo (Congo-Kinshasa)': 'cd',
  Denmark: 'dk',
  Djibouti: 'dj',
  Dominica: 'dm',
  'Dominican Republic': 'do',
  Ecuador: 'ec',
  Egypt: 'eg',
  'El Salvador': 'sv',
  'Equatorial Guinea': 'gq',
  Eritrea: 'er',
  Estonia: 'ee',
  Eswatini: 'sz',
  Ethiopia: 'et',
  Fiji: 'fj',
  Finland: 'fi',
  France: 'fr',
  Gabon: 'ga',
  Gambia: 'gm',
  Georgia: 'ge',
  Germany: 'de',
  Ghana: 'gh',
  Greece: 'gr',
  Grenada: 'gd',
  Guatemala: 'gt',
  Guinea: 'gn',
  'Guinea-Bissau': 'gw',
  Guyana: 'gy',
  Haiti: 'ht',
  'Holy See': 'va',
  Honduras: 'hn',
  Hungary: 'hu',
  Iceland: 'is',
  India: 'in',
  Indonesia: 'id',
  Iran: 'ir',
  Iraq: 'iq',
  Ireland: 'ie',
  Israel: 'il',
  Italy: 'it',
  Jamaica: 'jm',
  Japan: 'jp',
  Jordan: 'jo',
  Kazakhstan: 'kz',
  Kenya: 'ke',
  Kiribati: 'ki',
  Kuwait: 'kw',
  Kyrgyzstan: 'kg',
  Laos: 'la',
  Latvia: 'lv',
  Lebanon: 'lb',
  Lesotho: 'ls',
  Liberia: 'lr',
  Libya: 'ly',
  Liechtenstein: 'li',
  Lithuania: 'lt',
  Luxembourg: 'lu',
  Madagascar: 'mg',
  Malawi: 'mw',
  Malaysia: 'my',
  Maldives: 'mv',
  Mali: 'ml',
  Malta: 'mt',
  'Marshall Islands': 'mh',
  Mauritania: 'mr',
  Mauritius: 'mu',
  Mexico: 'mx',
  Micronesia: 'fm',
  Moldova: 'md',
  Monaco: 'mc',
  Mongolia: 'mn',
  Montenegro: 'me',
  Morocco: 'ma',
  Mozambique: 'mz',
  'Myanmar (formerly Burma)': 'mm',
  Namibia: 'na',
  Nauru: 'nr',
  Nepal: 'np',
  Netherlands: 'nl',
  'New Zealand': 'nz',
  Nicaragua: 'ni',
  Niger: 'ne',
  Nigeria: 'ng',
  'North Macedonia (formerly Macedonia)': 'mk',
  Norway: 'no',
  Oman: 'om',
  Pakistan: 'pk',
  Palau: 'pw',
  'Palestine State': 'ps',
  Panama: 'pa',
  'Papua New Guinea': 'pg',
  Paraguay: 'py',
  Peru: 'pe',
  Philippines: 'ph',
  Poland: 'pl',
  Portugal: 'pt',
  Qatar: 'qa',
  Romania: 'ro',
  Russia: 'ru',
  Rwanda: 'rw',
  'Saint Kitts and Nevis': 'kn',
  'Saint Lucia': 'lc',
  'Saint Vincent and the Grenadines': 'vc',
  Samoa: 'ws',
  'San Marino': 'sm',
  'Sao Tome and Principe': 'st',
  'Saudi Arabia': 'sa',
  Senegal: 'sn',
  Serbia: 'rs',
  Seychelles: 'sc',
  'Sierra Leone': 'sl',
  Singapore: 'sg',
  Slovakia: 'sk',
  Slovenia: 'si',
  'Solomon Islands': 'sb',
  Somalia: 'so',
  'South Africa': 'za',
  'South Korea': 'kr',
  'South Sudan': 'ss',
  Spain: 'es',
  'Sri Lanka': 'lk',
  Sudan: 'sd',
  Suriname: 'sr',
  Sweden: 'se',
  Switzerland: 'ch',
  Syria: 'sy',
  Tajikistan: 'tj',
  Tanzania: 'tz',
  Thailand: 'th',
  'Timor-Leste': 'tl',
  Togo: 'tg',
  Tonga: 'to',
  'Trinidad and Tobago': 'tt',
  Tunisia: 'tn',
  Turkey: 'tr',
  Turkmenistan: 'tm',
  Tuvalu: 'tv',
  Uganda: 'ug',
  Ukraine: 'ua',
  'United Arab Emirates': 'ae',
  UAE: 'ae',
  'United Kingdom': 'gb',
  UK: 'gb',
  'United States': 'us',
  USA: 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Vanuatu: 'vu',
  Venezuela: 've',
  Vietnam: 'vn',
  Yemen: 'ye',
  Zambia: 'zm',
  Zimbabwe: 'zw'
}

export const nationalityCodeDict = {
  Afghan: 'af',
  Albanian: 'al',
  Algerian: 'dz',
  Andorran: 'ad',
  Angolan: 'ao',
  'Antiguan and Barbudan': 'ag',
  Argentinian: 'ar',
  Argentine: 'ar',
  Armenian: 'am',
  Australian: 'au',
  Austrian: 'at',
  Azerbaijani: 'az',
  Bahamian: 'bs',
  Bahraini: 'bh',
  Bangladeshi: 'bd',
  Barbadian: 'bb',
  Belarusian: 'by',
  Belgian: 'be',
  Belizean: 'bz',
  Beninese: 'bj',
  Bhutanese: 'bt',
  Bolivian: 'bo',
  'Bosnian and Herzegovinian': 'ba',
  'Motswana (singular), Batswana (plural)': 'bw',
  Brazilian: 'br',
  Bruneian: 'bn',
  Bulgarian: 'bg',
  Burkinabe: 'bf',
  Burundian: 'bi',
  'Cabo Verdean': 'cv',
  Cambodian: 'kh',
  Cameroonian: 'cm',
  Canadian: 'ca',
  'Central African': 'cf',
  Chadian: 'td',
  Chilean: 'cl',
  Chinese: 'cn',
  Colombian: 'co',
  Comorian: 'km',
  Congolese: 'cg',
  'Costa Rican': 'cr',
  Croatian: 'hr',
  Cuban: 'cu',
  Cypriot: 'cy',
  Czech: 'cz',
  Danish: 'dk',
  Djiboutian: 'dj',
  Dominican: 'dm',
  Ecuadorian: 'ec',
  Egyptian: 'eg',
  Salvadoran: 'sv',
  'Equatorial Guinean': 'gq',
  Eritrean: 'er',
  Estonian: 'ee',
  Eswatini: 'sz',
  Ethiopian: 'et',
  Fijian: 'fj',
  Finnish: 'fi',
  French: 'fr',
  Gabonese: 'ga',
  Gambian: 'gm',
  Georgian: 'ge',
  German: 'de',
  Ghanaian: 'gh',
  Greek: 'gr',
  Grenadian: 'gd',
  Guatemalan: 'gt',
  Guinean: 'gn',
  'Guinea-Bissauan': 'gw',
  Guyanese: 'gy',
  Haitian: 'ht',
  'Holy See': 'va',
  Honduran: 'hn',
  Hungarian: 'hu',
  Icelandic: 'is',
  Indian: 'in',
  Indonesian: 'id',
  Iranian: 'ir',
  Iraqi: 'iq',
  Irish: 'ie',
  Israeli: 'il',
  Italian: 'it',
  Jamaican: 'jm',
  Japanese: 'jp',
  Jordanian: 'jo',
  Kazakhstani: 'kz',
  Kenyan: 'ke',
  Kiribati: 'ki',
  Kuwaiti: 'kw',
  Kyrgyzstani: 'kg',
  Laotian: 'la',
  Latvian: 'lv',
  Lebanese: 'lb',
  Mosotho: 'ls',
  Liberian: 'lr',
  Libyan: 'ly',
  Liechtensteiner: 'li',
  Lithuanian: 'lt',
  Luxembourger: 'lu',
  Malagasy: 'mg',
  Malawian: 'mw',
  Malaysian: 'my',
  Maldivian: 'mv',
  Malian: 'ml',
  Maltese: 'mt',
  Marshallese: 'mh',
  Mauritanian: 'mr',
  Mauritian: 'mu',
  Mexican: 'mx',
  Micronesian: 'fm',
  Moldovan: 'md',
  Monacan: 'mc',
  Monegasque: 'mc',
  Mongolian: 'mn',
  Montenegrin: 'me',
  Moroccan: 'ma',
  Mozambican: 'mz',
  Myanma: 'mm',
  Namibian: 'na',
  Nauruan: 'nr',
  Nepalese: 'np',
  Dutch: 'nl',
  'New Zealander': 'nz',
  Nicaraguan: 'ni',
  Nigerien: 'ne',
  Nigerian: 'ng',
  Macedonian: 'mk',
  Norwegian: 'no',
  Omani: 'om',
  Pakistani: 'pk',
  Palauan: 'pw',
  Palestinian: 'ps',
  Panamanian: 'pa',
  'Papua New Guinean': 'pg',
  Paraguayan: 'py',
  Peruvian: 'pe',
  Philippine: 'ph',
  Polish: 'pl',
  Portuguese: 'pt',
  Qatari: 'qa',
  Romanian: 'ro',
  Russian: 'ru',
  Rwandan: 'rw',
  'Kittian and Nevisian': 'kn',
  'Saint Lucian': 'lc',
  'Saint Vincent and the Grenadines': 'vc',
  Samoan: 'ws',
  'San Marinese': 'sm',
  'Sao Tomean': 'st',
  Saudi: 'sa',
  Senegalese: 'sn',
  Serbian: 'rs',
  Seychellois: 'sc',
  'Sierra Leonean': 'sl',
  Singaporean: 'sg',
  Slovak: 'sk',
  Slovenian: 'si',
  'Solomon Islander': 'sb',
  Somali: 'so',
  'South African': 'za',
  'South Korean': 'kr',
  'South Sudanese': 'ss',
  Spanish: 'es',
  'Sri Lankan': 'lk',
  Sudanese: 'sd',
  Surinamese: 'sr',
  Swedish: 'se',
  Swiss: 'ch',
  Syrian: 'sy',
  Tajik: 'tj',
  Tanzanian: 'tz',
  Thai: 'th',
  Timorese: 'tl',
  Togolese: 'tg',
  Tongan: 'to',
  'Trinidadian and Tobagonian': 'tt',
  Tunisian: 'tn',
  Turkish: 'tr',
  Turkmen: 'tm',
  Tuvaluan: 'tv',
  Ugandan: 'ug',
  Ukrainian: 'ua',
  Emirati: 'ae',
  British: 'gb',
  American: 'us',
  Uruguayan: 'uy',
  Uzbek: 'uz',
  'Ni-Vanuatu': 'vu',
  Venezuelan: 've',
  Vietnamese: 'vn',
  Yemeni: 'ye',
  Zambian: 'zm',
  Zimbabwean: 'zw'
}
</script>
